import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  topBar: {
    backgroundColor: '#000000',
    paddingHorizontal: 16,
    paddingVertical: 12,
    position: 'relative',
    zIndex: 1000,
  },
  topBarContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    flex: 1,
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  logo: {
    height: 40,
    width: 120,
    maxWidth: 120,
  },
  topBarIcons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  topBarIcon: {
    position: 'relative',
    padding: 4,
    marginLeft: 12,
  },
  notificationBadge: {
    position: 'absolute',
    top: 0,
    right: 0,
    backgroundColor: '#FF4444',
    borderRadius: 10,
    minWidth: 18,
    height: 18,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  notificationBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '600',
  },
  // Search Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'flex-start',
  },
  searchModal: {
    backgroundColor: '#18191A',
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    paddingTop: 60,
    paddingHorizontal: 16,
    paddingBottom: 20,
    maxHeight: '80%',
  },
  searchHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  searchInput: {
    flex: 1,
    backgroundColor: '#3A3B3C',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    color: '#FFFFFF',
    fontSize: 16,
    marginRight: 12,
  },
  searchCloseButton: {
    padding: 8,
  },
  searchResults: {
    maxHeight: 400,
  },
  searchResultsText: {
    color: '#B0B3B8',
    fontSize: 14,
    paddingVertical: 16,
  },
  // Notification Dropdown Styles
  notificationDropdown: {
    position: 'absolute',
    top: '100%',
    right: 16,
    width: 320,
    maxHeight: 400,
    backgroundColor: '#242526',
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    marginTop: 8,
    overflow: 'hidden',
  },
  notificationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#3A3B3C',
  },
  notificationHeaderText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
  },
  notificationList: {
    maxHeight: 320,
  },
  notificationItem: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#3A3B3C',
  },
  notificationItemContent: {
    flex: 1,
  },
  notificationItemText: {
    color: '#E4E6EB',
    fontSize: 14,
    marginBottom: 4,
  },
  notificationItemTime: {
    color: '#B0B3B8',
    fontSize: 12,
  },
  feedContainer: {
    flex: 1,
    backgroundColor: '#000000',
  },
  feedScrollView: {
    flex: 1,
  },
  feedContent: {
    padding: 12,
    paddingBottom: 20,
  },
  // Facebook Post Styles
  facebookPost: {
    backgroundColor: '#242526',
    borderRadius: 8,
    marginBottom: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  postHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  postHeaderInfo: {
    flex: 1,
  },
  postTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#E4E6EB',
    marginBottom: 4,
  },
  postTime: {
    fontSize: 13,
    color: '#B0B3B8',
  },
  shareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#3A3B3C',
    backgroundColor: 'transparent',
  },
  shareButtonText: {
    fontSize: 13,
    color: '#B0B3B8',
    marginLeft: 6,
    fontWeight: '400',
  },
  postImage: {
    width: '100%',
    borderRadius: 0,
    marginBottom: 12,
    backgroundColor: '#3A3B3C',
  },
  postContent: {
    fontSize: 15,
    color: '#E4E6EB',
    lineHeight: 22,
    marginBottom: 8,
  },
  bibleReferencePost: {
    fontSize: 14,
    color: '#B0B3B8',
    fontStyle: 'italic',
    marginTop: 8,
  },
  photoGridPost: {
    marginTop: 8,
  },
  photoRow: {
    flexDirection: 'row',
    marginBottom: 2,
  },
  photoItemLarge: {
    width: '100%',
    minHeight: 300,
    borderRadius: 0,
    backgroundColor: '#3A3B3C',
  },
  photoItemSmall: {
    flex: 1,
    height: 150,
    borderRadius: 0,
    overflow: 'hidden',
    marginLeft: 2,
    backgroundColor: '#3A3B3C',
  },
  photoItemContainer: {
    flex: 1,
    height: 150,
    borderRadius: 0,
    overflow: 'hidden',
    marginLeft: 2,
    position: 'relative',
    backgroundColor: '#3A3B3C',
  },
  photoItemFull: {
    width: '100%',
    height: '100%',
  },
  photoOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  photoOverlayText: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '600',
  },
  // Media Screen Styles
  mediaContainer: {
    flex: 1,
    backgroundColor: '#000000',
  },
  mediaScrollView: {
    flex: 1,
  },
  mediaContent: {
    padding: 16,
    paddingBottom: 20,
  },
  // Unified Media Tile Style
  mediaTile: {
    backgroundColor: '#1a1a1a',
    borderRadius: 20,
    marginBottom: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#2a2a2a',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  mediaTileImage: {
    width: '100%',
    height: 200,
    backgroundColor: '#2a2a2a',
  },
  mediaTileContent: {
    padding: 20,
  },
  mediaTileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  mediaTileIconBadge: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 125, 0, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  mediaTileTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: -0.3,
    flex: 1,
  },
  mediaTileDescription: {
    fontSize: 14,
    color: '#B0B0B0',
    lineHeight: 20,
  },
  screenContainer: {
    flex: 1,
    backgroundColor: '#000000',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  screenTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 10,
  },
  screenText: {
    fontSize: 16,
    color: '#CCCCCC',
    textAlign: 'center',
  },
});
